### ISSUE TITLE
Creating users

### ISSUE THREAD

**Issue by zeljkofilipin** [macbre/nodemw#127]
I am writing [Selenium tests for mediawiki/core](https://phabricator.wikimedia.org/source/mediawiki/browse/master/tests/selenium/) and I would like to speed up some tests by using the API instead of the web interface.

Am I missing it, or is there no built-in way of creating users?

Is making direct API calls the only way to go?

**Comment by macbre** [comment]
@zeljkofilipin, it seems that MediaWiki 1.21+ provides [an API for creating accounts](https://www.mediawiki.org/wiki/API:Account_creation) / [mediawiki.org sandbox](https://en.wikipedia.org/wiki/Special:ApiSandbox#action=createaccount&createreturnurl=http://example.com/&createtoken=29590a3037d325be70b93fb8258ed29257448cfb%2B%5C&username=Bob&password=ExamplePassword&retype=ExamplePassword&email=bob%40example.com&realname=Robert%20Example).

You can send "raw" API request in nodemw using `client.api.call` ([an example](https://github.com/macbre/nodemw/blob/devel/examples/smw.js)) as this feature is not supported by nodemw yet.

Hope that helps.

**Comment by zeljkofilipin** [comment]
Thanks @macbre. I'm probably missing it, but I could not find in the documentation how to send POST request.

```javascript
var bot = require('nodemw'),
	client = new bot({
		protocol: 'http',
		server: '127.0.0.1',
		port: '8080',
		path: '/w',
		debug: true
	}),
	params = {
		action: 'createaccount',
		createtoken: 'c27bca595899772c7c897b29188d4cb8595380b9+\\',
	};

client.api.call(params /* api.php parameters */, function(err /* Error instance or null */, info /* processed query result */, next /* more results? */, data /* raw data */) {
	console.log('\n-params-');
	console.log(params);
	console.log('\n-err-');
	console.log(err);
	console.log('\n-info-');
	console.log(info);
	console.log('\n-next-');
	console.log(next);
	console.log('\n-data-');
	console.log(data);
});
```

```
$ node createaccount.js 
info:    /usr/local/Cellar/node/8.1.2/bin/node /Users/z/Documents/gerrit/mediawiki/vagrant/mediawiki/api/createaccount.js
info:    nodemw v0.10.1 (node.js v8.1.2; darwin x64)
info:    Using <http://127.0.0.1:8080/w/api.php> as API entry point
info:    ----
debug:   API action: createaccount
debug:   GET <http://127.0.0.1:8080/w/api.php?action=createaccount&createtoken=c27bca595899772c7c897b29188d4cb8595380b9%2B%5C&format=json>
error:   Error returned by API: The following parameter was found in the query string, but must be in the POST body: createtoken.
data:     code=mustpostparams, info=The following parameter was found in the query string, but must be in the POST body: createtoken., *=See http://127.0.0.1:8080/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.

-params-
{ action: 'createaccount',
  createtoken: 'c27bca595899772c7c897b29188d4cb8595380b9+\\',
  format: 'json' }

-err-
Error: Error returned by API: The following parameter was found in the query string, but must be in the POST body: createtoken.
    at Request._callback (/Users/z/Documents/gerrit/mediawiki/vagrant/mediawiki/node_modules/nodemw/lib/api.js:219:14)
    at Request.self.callback (/Users/z/Documents/gerrit/mediawiki/vagrant/mediawiki/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/z/Documents/gerrit/mediawiki/vagrant/mediawiki/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/Users/z/Documents/gerrit/mediawiki/vagrant/mediawiki/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)

-info-
undefined

-next-
undefined

-data-
undefined
```

**Comment by zeljkofilipin** [comment]
Adding `method: 'POST'` to `params` did not help. :)

```javascript
...
	params = {
		action: 'createaccount',
		createtoken: 'c27bca595899772c7c897b29188d4cb8595380b9+\\',
		method: 'POST'
	};
...
```

```
$ node createaccount.js
...
debug:   GET <http://127.0.0.1:8080/w/api.php?action=createaccount&createtoken=c27bca595899772c7c897b29188d4cb8595380b9%2B%5C&method=POST&format=json>
...
```

**Comment by zeljkofilipin** [comment]
Thanks to @hashar this is what I have so far:

```javascript
var bot = require('nodemw'),
	client = new bot({
		protocol: 'http',
		server: '127.0.0.1',
		port: '8080',
		path: '/w',
		debug: true
	}),
	params = {
		action: 'createaccount',
		createtoken: 'ff35e8a9cd3383562d448badae7e92805953a5a7+\\'
	};

client.api.call(params /* api.php parameters */, function(err /* Error instance or null */, info /* processed query result */, next /* more results? */, data /* raw data */, ) {
	console.log('\n-params-');
	console.log(params);
	console.log('\n-err-');
	console.log(err);
	console.log('\n-info-');
	console.log(info);
	console.log('\n-next-');
	console.log(next);
	console.log('\n-data-');
	console.log(data);
}, 'POST');
```

```
$ node createaccount.js 
info:    /usr/local/Cellar/node/8.1.2/bin/node /Users/z/Documents/gerrit/mediawiki/vagrant/mediawiki/api/createaccount.js
info:    nodemw v0.10.1 (node.js v8.1.2; darwin x64)
info:    Using <http://127.0.0.1:8080/w/api.php> as API entry point
info:    ----
debug:   API action: createaccount
debug:   POST <http://127.0.0.1:8080/w/api.php>
debug:   POST fields: action, createtoken, format
error:   Error returned by API: Invalid CSRF token.
data:     code=badtoken, info=Invalid CSRF token., *=See http://127.0.0.1:8080/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.

-params-
{ action: 'createaccount',
  createtoken: 'ff35e8a9cd3383562d448badae7e92805953a5a7+\\',
  format: 'json' }

-err-
Error: Error returned by API: Invalid CSRF token.
    at Request._callback (/Users/z/Documents/gerrit/mediawiki/vagrant/mediawiki/node_modules/nodemw/lib/api.js:219:14)
    at Request.self.callback (/Users/z/Documents/gerrit/mediawiki/vagrant/mediawiki/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/z/Documents/gerrit/mediawiki/vagrant/mediawiki/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/Users/z/Documents/gerrit/mediawiki/vagrant/mediawiki/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)

-info-
undefined

-next-
undefined

-data-
undefined
```

**Comment by zeljkofilipin** [comment]
Thanks @macbre and @hashar, this works.

```javascript
var bot = require('nodemw'),
	client = new bot({
		protocol: 'http',
		server: '127.0.0.1',
		port: '8080',
		path: '/w',
		debug: true
	}),
	params = {
		action: 'query',
		meta: 'tokens',
		type: 'createaccount'
	};

client.api.call(params /* api.php parameters */, function(err /* Error instance or null */, info /* processed query result */, next /* more results? */, data /* raw data */) {

	// log all the things
	console.log('\n-params-');
	console.log(params);
	console.log('\n-err-');
	console.log(err);
	console.log('\n-info-');
	console.log(info);
	console.log('\n-next-');
	console.log(next);
	console.log('\n-data-');
	console.log(data);
	console.log('\n-data.query.tokens.createaccounttoken-');
	console.log(data.query.tokens.createaccounttoken);

	var params = {
			action: 'createaccount',
			createreturnurl: 'http://127.0.0.1:8080/',
			createtoken: data.query.tokens.createaccounttoken,
			username: 'User-2',
			password: 'password-2',
			retype: 'password-2',
		};

	client.api.call(params /* api.php parameters */, function(err /* Error instance or null */, info /* processed query result */, next /* more results? */, data /* raw data */, ) {

		// log all the things
		console.log('\n-params-');
		console.log(params);
		console.log('\n-err-');
		console.log(err);
		console.log('\n-info-');
		console.log(info);
		console.log('\n-next-');
		console.log(next);
		console.log('\n-data-');
		console.log(data);

	}, 'POST');

});
```

```
$ node createaccount.js 
info:    /usr/local/Cellar/node/8.1.2/bin/node /Users/z/Documents/gerrit/mediawiki/vagrant/mediawiki/api/createaccount.js
info:    nodemw v0.10.1 (node.js v8.1.2; darwin x64)
info:    Using <http://127.0.0.1:8080/w/api.php> as API entry point
info:    ----
debug:   API action: query
debug:   GET <http://127.0.0.1:8080/w/api.php?action=query&meta=tokens&type=createaccount&format=json>

-params-
undefined

-err-
null

-info-
{ tokens: { createaccounttoken: '4ce79324b7270cce573bf9fa9c8ad24c5954c90a+\\' } }

-next-
undefined

-data-
{ batchcomplete: '',
  query: { tokens: { createaccounttoken: '4ce79324b7270cce573bf9fa9c8ad24c5954c90a+\\' } } }

-data.query.tokens.createaccounttoken-
4ce79324b7270cce573bf9fa9c8ad24c5954c90a+\
debug:   API action: createaccount
debug:   POST <http://127.0.0.1:8080/w/api.php>
debug:   POST fields: action, createreturnurl, createtoken, username, password, retype, format

-params-
{ action: 'createaccount',
  createreturnurl: 'http://127.0.0.1:8080/',
  createtoken: '4ce79324b7270cce573bf9fa9c8ad24c5954c90a+\\',
  username: 'User-2',
  password: 'password-2',
  retype: 'password-2',
  format: 'json' }

-err-
null

-info-
{ status: 'PASS', username: 'User-2' }

-next-
undefined

-data-
{ createaccount: { status: 'PASS', username: 'User-2' } }
```
