### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string

### ISSUE THREAD

**Issue by Sebbyastian** [macbre/nodemw#148]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.dirname (path.js:1271:5)
    at new api (/home/dev/node_modules/nodemw/lib/api.js:176:19)
    at new bot (/home/dev/node_modules/nodemw/lib/bot.js:51:15)

When trying examples within node.js this occurs...

**Comment by Sebbyastian** [comment]
Eh, I don't know what I did qrong, but it's not backreferencing like I intended...

https://github.com/macbre/nodemw/pull/149/files#diff-9ccb9b0bdd7e6cd41dfc6512731c2719
