### ISSUE TITLE
Possible bug in upload handling (when other parameters are provided)

### ISSUE THREAD

**Issue by minecrafter** [macbre/nodemw#63]
Note that this only happens when other parameters are provided. The summary-only parameters seem to work fine for some reason. I'm using iojs v2.1.0.

Triggering code (very simple):

            async.each(Object.keys(nameToUrls), function(file, cb) {
                var from = nameToUrls[file];
                bot.uploadByUrl(file, from, { text: 'some text',
                    comment: 'autoupload file',
                    ignorewarnings: false }, function(err, res) {
                    if (err) {
                        logger.error('Unable to upload ' + file, err);
                        return cb();
                    }

                    logger.info('Uploaded ' + file + ' from ' + from);
                    cb();
                });
            }, function() {
                logger.info('Uploaded ' + lang);
            });

Error:

    error:   Unable to upload <file>
    Error: Request to API failed:     Error: Argument error, options.body.
        at Request._callback (/home/tux/IdeaProjects/archivesbot/node_modules/nodemw/lib/api.js:162:14)
        at self.callback (/home/tux/IdeaProjects/archivesbot/node_modules/nodemw/node_modules/request/request.js:354:22)
        at emitOne (events.js:77:13)
        at Request.emit (events.js:169:7)
        at Request.init (/home/tux/IdeaProjects/archivesbot/node_modules/nodemw/node_modules/request/request.js:609:12)
        at new Request (/home/tux/IdeaProjects/archivesbot/node_modules/nodemw/node_modules/request/request.js:265:8)
        at request (/home/tux/IdeaProjects/archivesbot/node_modules/nodemw/node_modules/request/index.js:56:10)
        at Object.module.exports.doRequest (/home/tux/IdeaProjects/archivesbot/node_modules/nodemw/lib/api.js:157:3)
        at Object.<anonymous> (/home/tux/IdeaProjects/archivesbot/node_modules/nodemw/lib/api.js:236:15)
        at /home/tux/IdeaProjects/archivesbot/node_modules/nodemw/lib/api.js:59:4
    _http_outgoing.js:429
            throw new TypeError('first argument must be a string or Buffer');
                  ^
    TypeError: first argument must be a string or Buffer
        at ClientRequest.OutgoingMessage.write (_http_outgoing.js:429:11)
        at Request.write (/home/tux/IdeaProjects/archivesbot/node_modules/nodemw/node_modules/request/request.js:1510:25)
        at /home/tux/IdeaProjects/archivesbot/node_modules/nodemw/node_modules/request/request.js:703:18
        at Array.forEach (native)
        at end (/home/tux/IdeaProjects/archivesbot/node_modules/nodemw/node_modules/request/request.js:702:21)
        at Immediate._onImmediate (/home/tux/IdeaProjects/archivesbot/node_modules/nodemw/node_modules/request/request.js:734:7)
        at processImmediate [as _immediateCallback] (timers.js:368:17)

**Comment by macbre** [comment]
@minecrafter, please log the values of `file` and `from` variables or create the nodemw client with `debug` config option set to `true` - this will make console logging more verbose.

**Comment by minecrafter** [comment]
Here's a run of the script with `uploadByUrl`: http://paste.ubuntu.com/11726991/

For now I just reimplemented this part of the script using MediaWiki's native upload-by-URL capabilities, though I'd love to use a nicer API for this.

**Comment by macbre** [comment]
The log contains huge amount of repeated files and URL fetches.

**Comment by minecrafter** [comment]
Modified the code to upload one random file from the selection, here's the log from that: http://paste.ubuntu.com/11727420/

**Comment by macbre** [comment]
@minecrafter, I somehow missed that you're using `iojs`. Are you able to run your code on node.js and reproduce the issue?

**Comment by minecrafter** [comment]
I can take a look at the issue with node 0.10 in a bit.

**Comment by minecrafter** [comment]
I managed to get some time to look into the issue. Under node 0.10 the issue is still present.

**Comment by macbre** [comment]
@minecrafter: [logs from iojs](http://paste.ubuntu.com/11727420/) are kind of mysterious (`Request to API failed: %s Error: Argument error, options.body.` - not showing the parameters). Can you provide logs from nodejs run?

**Comment by minecrafter** [comment]
I'm going to update to ~0.7.0 and try it again. You want node 0.10 or 4.x?

**Comment by macbre** [comment]
Let's try with 4.x - the latest the better ;)

**Comment by minecrafter** [comment]
Doesn't work: https://gist.github.com/minecrafter/394ed57817648a32c6a4

Running node v4.0.0

**Comment by macbre** [comment]
@minecrafter: can you skip `ignorewarnings: false` option in a call to `uploadByUrl`? Or replace it with  `"0"` (as a string)?

**Comment by minecrafter** [comment]
Looks like that worked.

**Comment by macbre** [comment]
Great!
