### ISSUE TITLE
Token error when editing

### ISSUE THREAD

**Issue by ValentinBrclz** [macbre/nodemw#87]
Hello,

I often encounter token errors (Error: Invalid token) and after doing some changes to my code, I realised that the error was made because of the concurrency of the requests.

I guess that a token has to be used directly to successfully edit a page. If a second token is asked in the meantime, the edit will fail with the aforementioned error.

Best regards,
Val'

**Comment by ValentinBrclz** [comment]
I encountered it again today, errors comes from `doEdit`. 

	Error: Edit failed: Error: Error returned by API: Invalid CSRF token.
		at ...\WP-OubliSignature-Bot\node_modules\nodemw\lib\bot.js:514:16
		at Request._callback (...\WP-OubliSignature-Bot\node_modules\nodemw\lib\api.js:219:5)
		at Request.self.callback (...\WP-OubliSignature-Bot\node_modules\request\request.js:186:22)
		at emitTwo (events.js:106:13)
		at Request.emit (events.js:191:7)
		at Request.<anonymous> (...\WP-OubliSignature-Bot\node_modules\request\request.js:1081:10)
		at emitOne (events.js:96:13)
		at Request.emit (events.js:188:7)
		at IncomingMessage.<anonymous> (...\WP-OubliSignature-Bot\node_modules\request\request.js:1001:12)
		at IncomingMessage.g (events.js:291:16)

**Comment by PaulWieland** [comment]
I believe I am encountering this same error. I'm using nodemw in a NodeRED flow.

I have a global `bot` object which is refreshed daily.

Then I have another flow which updates the wiki (sometimes thousands of times per day). A small percentage of these updates fail with `Error returned by API: Invalid CSRF token`, but I'm not quite sure why.

**Comment by vid** [comment]
Is there a solution to this? Thanks.
